### ISSUE TITLE
Battery usage support

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fetch#46]
Hi guys, 

I'm currently working on adding support for the new battery function to the 
other OS we support. I don't own anything with a battery so I'll need some help
testing. 

Here's the TODO for the battery function:

- Add support for all platforms
    - The only OS without support are the BSDs as we have no one to help test.
    - I'll be getting a laptop soon so support will come eventually.
- ~~Add an option to only print the first battery or X number of batteries.~~
    - https://github.com/dylanaraps/fetch/commit/bb48caec703c1b537e807de90afd3d6181ff78c6
- ~~Add an option to print all batteries on a single line.~~
    - https://github.com/dylanaraps/fetch/commit/6cd2881962adac36a01e6029c6ecfc63f2f07662

**Comment by dylanaraps** [comment]
OS X users, what does this command output?

```sh
pmset -g batt | grep -o '[0-9]*%' | tr -d %
```

**Comment by mclado** [comment]
You can tag me next time for OS X test, I will respond to you much faster. 
First one is `100`.
Second one is :
- 1. AdapterInfo 0
- 2. Amperage 0
- 3. AvgTimeToEmpty 65535
- 4. AvgTimeToFull 65535
- 5. BatteryInstalled Yes
- 6. BatteryInvalidWakeSeconds 30
- 7. BatterySerialNumber XXX (don't want to share)
- 8. BootPathUpdated 1454405207
- 9. CellVoltage (4090,4112,4085,0)
- 10. CurrentCapacity 6014
- 11. CycleCount 340
- 12. DesignCapacity 6330
- 13. DesignCycleCount9C 1000
- 14. DeviceName bq20z451
- 15. ExternalChargeCapable Yes
- 16. ExternalConnected Yes
- 17. FirmwareSerialNumber 1
- 18. FullPathUpdated 1454421662
- 19. FullyCharged Yes
- 20. IOGeneralInterest IOCommand
- 21. InstantAmperage 0
- 22. InstantTimeToEmpty 174
- 23. IsCharging No
- 24. LegacyBatteryInfo {Amperage=0,Flags=5,Capacity=6059,Current=6014,Voltage=12287,Cycle
- 25. Location 0
- 26. ManufactureDate 17545
- 27. ManufacturerData <000000000702000a038900000XXXXXXXXXXXX (don't want to share)>
- 28. MaxCapacity 6059
- 29. MaxErr 1
- 30. OperationStatus 58435
- 31. PackReserve 200
- 32. PermanentFailureStatus 0
- 33. PostChargeWaitSeconds 120
- 34. PostDischargeWaitSeconds 120
- 35. Temperature 2943
- 36. TimeRemaining 0
- 37. UserVisiblePathUpdated 1454421842
- 38. Voltage 12287

What are you planing to display? I think it would be nice to display current battery status and then options for cycle count, current capacity & design capacity and also fully charged & is charging.

**Comment by mclado** [comment]
Win 10 git bash:
$ WMIC Path Win32_Battery
Availability  BatteryRechargeTime  BatteryStatus  Caption           Chemistry  ConfigManagerErrorCode  ConfigManagerUserConfig  CreationClassNam                                    e  Description       DesignCapacity  DesignVoltage  DeviceID     ErrorCleared  ErrorDescription  EstimatedChargeRemaining  EstimatedRunTime  Exp                                    ectedBatteryLife  ExpectedLife  FullChargeCapacity  InstallDate  LastErrorCode  MaxRechargeTime  Name     PNPDeviceID  PowerManagementCapabiliti                                    es  PowerManagementSupported  SmartBatteryVersion  Status  StatusInfo  SystemCreationClassName  SystemName       TimeOnBattery  TimeToFullCharge                                    
2                                  2              Internal Battery  2                                                           Win32_Battery                                          Internal Battery                  12112          ASUSXXXXX                                  98                        12312121                                                                                                                                                  XXXXX               {1}                                                              FALSE                                          OK                  Win32_ComputerSystem     DESKTOP-XXXXXX                                                                    
 
 
$ WMIC PATH Win32_Battery Get EstimatedChargeRemaining
EstimatedChargeRemaining
98

**Comment by dylanaraps** [comment]
Thanks for the reply and for testing the commands for me!

Currently the battery function prints in this format:

```sh
# Single battery
Battery: XX%

# Multiple
Battery0: XX%
Battery1: XX%

# Shorthand Multiple
Battery: XX%, XX%
```

For now we'll leave battery support at just usage %, I'm getting a laptop for uni in a few weeks so I'll be able dedicate time to implement `is charging`, `current capacity` etc properly.

I'll add support for `OS X` in the morning, it's 2 am here so I'll be heading off to bed. For the `Windows` output is the 2nd command's output the percentage? It's weird that it's just `9` as the first command shows it as `98`.

**Comment by dylanaraps** [comment]
One more thing, what does this output on `OS X`?

```sh
cat /sys/class/power_supply/BAT*/capacity
```

**Comment by mclado** [comment]
Yeah sry, its 98, just copy/paste things. 

Ok great, if I had time I would love to help you, but I have exams those days. Meybe after them if you like.

Nothing, because I can't even cd into /sys like it doesn't exist? The only thing starting on s is sbin.

Sleep well.

**Comment by dylanaraps** [comment]
Is it possible for an OS X system to have multiple batteries in use at the same time?

**Comment by mclado** [comment]
Hmm I am 99% sure that this is not possible but I was just thinking about the new Macbook 12 which has multiple layers or batteries, maybe some info will be different?

But I don't think there will this "multibattery problem" on OS X so don't waste your time implementing this imo.

**Comment by dylanaraps** [comment]
I've added support for `Mac OS X` and `Windows`, please test it out!

The config options are related to multi-battery and won't work on OS X and Windows for now. 
To add support for multi-battery output on Windows I'll need to know the command output so I can,
parse it correctly which means that we'll have to wait for someone with a multi-battery laptop to open 
an issue.

**Comment by mclado** [comment]
OS X works like it should, check!

**Comment by dylanaraps** [comment]
Awesome!

How about Windows?

**Comment by mclado** [comment]
Nope, something is not ok.

```
 Disk: 137G / 154G (90%)
 Battery: %

```

**Comment by dylanaraps** [comment]
I just pushed a fix to master, it should work now.

**Comment by mclado** [comment]
Still not working for me. Using git bash instead of cygwin should't be the problem, right?

**Comment by dylanaraps** [comment]
It shouldn't be an issue, does this command work on its own?

```sh
wmic Path Win32_Battery get EstimatedChargeRemaining /value
```

**Comment by mclado** [comment]
Oh wait a sec, it is! Just found out because I tried manually. I am getting "Invalid GET Expression" (in git bash). But the command in cygwin works well. I can't get this cygwin to work as it should so I could run full fetch script. Running manually lines 1240 - 1245 gives me `$ echo $battery 
100 100 %`

**Comment by dylanaraps** [comment]
I've fixed the doubled usage in my local branch, thanks for finding it. 

What about this command in git bash?:

```sh
cmd /c wmic Path Win32_Battery get EstimatedChargeRemaining /value
```

**Comment by dylanaraps** [comment]
I just pushed a fix to master for the doubled battery usage.

**Comment by dylanaraps** [comment]
If the command above doesn't work in git bash then I'm going to close this issue as it works in CYGWIN.
