### ISSUE TITLE
Add MOC support for current song

### ISSUE THREAD

**Issue by kelaun** [dylanaraps/fetch#72]
It would be nice to also support MOC for the currently playing song

**Comment by dylanaraps** [comment]
Does MOC have a command that prints the current playing song?

**Comment by kelaun** [comment]
Just looked into it.
You can know if moc is currently running with:
`pgrep "mocp" > /dev/null`
After that you can know the state (playing, paused, stopped, ...) with:
`mocp -Q "%state"`
And finally you can get the playing song with:
`mocp -Q "%artist - %song"`

**Comment by dylanaraps** [comment]
Awesome!

I'll add support now. :)

**Comment by kelaun** [comment]
Great, thanks!

**Comment by dylanaraps** [comment]
Done.

I'll add a rewrite of `getsong` to my todo list that adds process checking
and playback state. For now the current behaviour should be sufficient.

**Comment by kelaun** [comment]
It's not working, when I enter 
`type -p mocp >/dev/null 2>&1`
in my terminal I get nothing back, but mocp is running

**Comment by kelaun** [comment]
Just realised it is normal I get nothing back haha, but still not working. Weird

**Comment by dylanaraps** [comment]
What about this?:

```sh
type -p moc >/dev/null 2>&1
```

**Comment by dylanaraps** [comment]
Weird.

**Comment by dylanaraps** [comment]
I'm installing moc now.

**Comment by dylanaraps** [comment]
It works fine for me!

**Comment by kelaun** [comment]
Weird. It works fine for me when using:
if pgrep "mocp" > /dev/null; then
        mocpstate=$(mocp -Q "%state")
        mocpplaying=$(mocp -Q "%artist - %song")
fi

**Comment by dylanaraps** [comment]
I'll rewrite `getsong` now then and it should work for you. :)

**Comment by kelaun** [comment]
Thanks!

**Comment by dylanaraps** [comment]
I've rewritten it to use `pgrep` instead of `type`. State support will 
come later as it'll be a pain to get it working between players. :)

**Comment by kelaun** [comment]
I can confirm it is working now, thanks!

**Comment by dylanaraps** [comment]
No problem!
