### ISSUE TITLE
Running this on OS X under iTerm2, I get "integer expression expected"

### ISSUE THREAD

**Issue by MindTooth** [dylanaraps/fetch#92]
Hi,

I've just tried to make a formula for Homebrew on OS X.  However, I get the following error:
<pre>~ $ fetch
MindTooth@MacToothPro.local
---------------------------
OS: Mac OS X 10.11.3 15D21 x86_64
Kernel: 15.3.0
Uptime: up 1 day, 16 hours, 5 minutes
Packages: 60
Shell: /usr/local/bin/fish
Window Manager: _NET_SUPPORTING_WM_CHECK: window id # 0x400001
/usr/local/bin/fetch: line 2552: [: : integer expression expected
</pre>

I'm on El Capitan, and iTerm2.  Is there a reason Windows Manager is showing when just running inside iTerm2?  That information is somewhat irrelevant to me.

Thanks for the tool though :-)

**Comment by dylanaraps** [comment]
The window manager output you're getting should only appear when 'X' is running,
what's the output of this command?:

```sh
echo "$DISPLAY"
```

**Comment by MindTooth** [comment]
Thank you for the fast reply!

<pre>~ $ echo "$DISPLAY"
/private/tmp/com.apple.launchd.vyzwY7JTfF/org.macosforge.xquartz:0</pre>

**Comment by dylanaraps** [comment]
It seems as though you're running `X` which is why the window manager stuff is appearing.
What we may have to do is disable the xprop stuff on OS X as this has happened to other
people too.

https://en.wikipedia.org/wiki/XQuartz

About the Integer error on line `2552`, add `set -x` to line 2 of the script and upload the
output somewhere. That should tell me why it's erroring out.

**Comment by MindTooth** [comment]
Does this suffice: https://gist.github.com/MindTooth/083bfc462ced08e9fc26

Not that knowledgeable about redirect, etc. in BASH.

**Comment by dylanaraps** [comment]
Both issues should be fixed now, please test it out. :)

**Comment by MindTooth** [comment]
I'm able to run it now :-)  Still an issue though:
<pre>$ fetch
 usr/local/bin/fetch: line 1730: ${ascii_distro,,}: bad substitution
MindTooth@MacToothPro.local
---------------------------
OS: Mac OS X 10.11.3 15D21 x86_64
Kernel: 15.3.0
Uptime: up 2 days, 20 hours, 43 minutes
Packages: 59
Shell: /usr/local/bin/fish
Window Manager: Quartz Compositor
CPU: Intel Core2 Duo     P8600  @ 2.40GHz
GPU: NVIDIA GeForce 9400MNVIDIA GeForce 9600M GT
Memory: 1245MB / 8192MB</pre>

**Comment by dylanaraps** [comment]
Weird, 

- What's your `bash` version?
- Add `set -x` to line 2 and upload the output somewhere.

it also looks like you have a duplicated GPU output and a large
amount of whitespace in the CPU output. I'll try to fix those too.

**Comment by MindTooth** [comment]
https://gist.github.com/MindTooth/9b8a4cef5f992041877a

Everything's there :-)

**Comment by dylanaraps** [comment]
It looks like you're using `bash 3`, fetch only supports `bash 4+` that's why you're
getting the `bad substitution` error. You can install bash 4 using homebrew and
the issue will be fixed.

I've fixed the GPU and CPU outputs and the fixes are already in master.

**Comment by mclado** [comment]
Well, I just reinstalled my OS X and found out same problem. Will report about solution!

**Comment by mclado** [comment]
Is this a typo in line 1607 `ascii=${ascii_distro,,}`?
Changing it to `ascii=${ascii_distro}` works fine.

**Comment by dylanaraps** [comment]
What's your `bash` version?

**Comment by mclado** [comment]
`echo $BASH_VERSION
3.2.57(1)-release`
I never ever before updated bash (as far as I remember, meybe it updated with some programs?)

But I found a solution!
I installed command line tools (as described here http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/) and the thing is working for me.
@MindTooth do you have those installed?

**Comment by mclado** [comment]
If this also fixes MindTooth's problem, then you should add this to required dependencies.

**Comment by dylanaraps** [comment]
Fetch only supports bash **4.0+**, you'll have to install it through homebrew or find
another solution as OS X comes with `3.X`.

**Comment by dylanaraps** [comment]
Does `command line tools` also update bash?

**Comment by dylanaraps** [comment]
Actually, what I'll do is use `$BASH_VERSION` to possibly add support for bash 3.xx.

**Comment by mclado** [comment]
Check out the list, it's not there.

Yeah, nice

**Comment by dylanaraps** [comment]
Done, I've added support for bash 3.0+. Please test it out.

**Comment by mclado** [comment]
Works well, good job!

Also, typo under installation/other...it's El Capitan not El Captain.

**Comment by dylanaraps** [comment]
I'm closing this now as the issues have been fixed.
